version: '3'

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    container_name: rethinkdb
    restart: unless-stopped
    volumes:
      - rethink_data_prod:/data
    networks:
      - traefik

  horizon:
    image: rethinkdb/horizon
    container_name: horizon
    restart: unless-stopped
    command: su -s /bin/sh horizon -c "hz serve --dev --connect rethinkdb://rethinkdb:28015 --bind all /usr/app"
    volumes:
      #need to get rid of this.  use dockerfile?
      - ./client:/usr/app
    depends_on:
      - rethinkdb
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.horizon.rule= PathPrefix(`/horizon`)
      - traefik.http.routers.horizon.service=horizon
      - traefik.http.routers.horizon.tls.certresolver=letsencryptresolver
      - traefik.http.services.horizon.loadbalancer.server.port=8181

  django:
    build:
      context: ./server/
      dockerfile: dockerfile-prod
    container_name: django
    restart: unless-stopped
    command: bash -c "gunicorn redctf.wsgi:application --log-file=- --bind 0.0.0.0:8000"
    volumes:
      # So that Django can interact with Docker host
      - /var/run/docker.sock:/var/run/docker.sock
      # for serving django admin css, etc.
      - static_volume_prod:/home/app/redctf/static
      - media_volume_prod:/home/app/redctf/media
    environment:
      - RDB_HOST=rethinkdb
      - RDB_PORT=28015
    depends_on:
      - horizon
      - postgres
    networks:
      - traefik
    env_file:
      - ./server/.env.prod

  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    networks:
      - traefik
    env_file:
      - ./server/.env.prod.db

  reverse-proxy:
      # The official v2.0 Traefik docker image
      image: traefik:v2.0.6
      container_name: reverse-proxy
      restart: unless-stopped
      command:
        # Enable for debug logging
        #- "--log.level=DEBUG"
        - "--accesslog=true"
        # Enable for the web UI
        #- "--api.insecure=true"
        #- "--api.dashboard=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.letsencryptresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.letsencryptresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        - "--certificatesresolvers.letsencryptresolver.acme.email=jrue3084@gmail.com"
        - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      ports:
        # The HTTP(s) ports
        - "80:80"
        - "443:443"
        # The Web UI (enabled by --api.insecure=true)
        #- "8080:8080"
      volumes:
        - letsencrypt_data_prod:/letsencrypt
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=PathPrefix(`/dashboard`)
        - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
        # Enable for the web UI
        #- "traefik.http.routers.api.service=api@internal"
      depends_on:
        - nginx
      networks:
        - traefik

  nginx:
    build:
      context: .
      dockerfile: ./server/nginx/dockerfile-nginx
    container_name: nginx
    restart: unless-stopped  
    volumes:
      # for serving client (react) files
      - static_volume_prod:/home/app/redctf/static
      - media_volume_prod:/home/app/redctf/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=PathPrefix(`/`)
      - traefik.http.routers.nginx.service=nginx-backend
      - traefik.http.routers.nginx.tls.certresolver=letsencryptresolver
      - traefik.http.services.nginx-backend.loadbalancer.server.port=8080
    depends_on:
      - django
    networks:
      - traefik

networks:
  traefik:

volumes:
  rethink_data_prod:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:
  letsencrypt_data_prod: